name = "The Republic"
author = "[REDACTED] Serenity Tan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d1d92a416fe4b1f6631c6c7d87eb65bf5eda7527a8ab31e5924ab885db0f361"

[versions]
forge = "40.3.0"
minecraft = "1.18.2"
