name = "The Republic"
author = "[REDACTED] Serenity Tan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6ac201b5a5e029008ed1431d9281fbb06920ea1fbf84ec14836c23571c80498"

[versions]
forge = "40.3.0"
minecraft = "1.18.2"
