name = "The Republic"
author = "[REDACTED] Serenity Tan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0113890734452a728cee876a3d7c885509e088213676e96afe1405a613db0efa"

[versions]
forge = "40.3.0"
minecraft = "1.18.2"
