name = "The Republic"
author = "[REDACTED] Serenity Tan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "173724434afead1106296e04e7eb0c454c0de2a9f52986d2bf151dfe44899a84"

[versions]
forge = "40.3.0"
minecraft = "1.18.2"
